### ISSUE TITLE
Python error during eSim2.3 on Ubuntu 23.04

### ISSUE THREAD

**Issue by pointless-user** [FOSSEE/eSim#249]
Hi,

I'm trying to install eSim2.3 on  a fresh and updated Ubuntu 23.04. 
I'm quiet a newbe with the terminal / Ubuntu, but forced to use it to install eSim2.3

After using these lines,  $ chmod +x install-eSim.sh  and    $ ./install-eSim.sh --install
I got a seemingly Phyton error.  Is there a way to solve this easily?  

Ps, in about a week I got more time to play around with stuff, now waiting for a new hip and need the pc in  hospital.
Afraid to screw things up.

Thanks in advance.

Processing triggers for libc-bin (2.37-0ubuntu2) ...
Installing Watchdog........................
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

Error! Kindly resolve above error(s) and try again.

Aborting Installation...

**Comment by Eyantra698Sumanto** [comment]
@pointless-user 

Sorry for delayed reply. As of now eSim is only supported on Ubuntu 18.04 and Ubuntu 20.04. We are soon upgrading eSim for higher Ubuntu versions as well. Till then bear with us and please try out eSim on Ubuntu 18.04 and Ubuntu 
 20.04. Please refer to the following link for more details and installation steps:
 https://esim.fossee.in/downloads
 
Also, in order to work on Ubuntu you will need to get used to the terminal and Linux shell commands.

Please feel free to ask any more queries.

Regards,
Sumanto
